blank_issues_enabled: false
contact_links:
  - name: Question / Support
    url: https://github.com/blendbyte/filament-title-with-slug/discussions
    about: For usage questions and general support, please use GitHub Discussions.
